In [1]:
import numpy as np
from img_loader import DatasetLoader
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from PIL import Image, ImageOps
from sklearn.preprocessing import MinMaxScaler
import scipy.misc
from PIL import ImageEnhance, ImageOps
import cv2
import matplotlib.pyplot as pp
import random
from glob import glob
from numpy import argmax
from scipy.misc import toimage
import json

In [13]:
b_directory = 'maps_test_tf'
files_path = glob(b_directory + "/*/*/*.json")

In [17]:
splitted = files_path[0].split('/')
splitted

['maps_test_tf', 'Faces', 'image_0111.jpg', 'resuts.json']

In [15]:
with open(files_path[0]) as data_file:    
    data = json.load(data_file)
print(data)

{'predicted': '1', 'true_label': '1'}


In [16]:
data["predicted"]

'1'

In [ ]:
if data["predicted"] != data["true_label"]:

In [20]:
img_path = glob(b_directory + '/' + splitted[1] + '/' + splitted[2] + '/*.tiff')

In [2]:
# dans quel sens on peux flatten un pil getdata et une cv2 image?
folder_read = '/home/lux/dev/Bachelor-2017/keras/dataset_black_bg/Apple___Apple_scab/0a5e9323-dbad-432d-ac58-d291718345d9___FREC_Scab 3417_final_masked.jpg'
im = cv2.imread(folder_read, cv2.IMREAD_GRAYSCALE)
cv2.imwrite('out.jpg', im)
im.shape

(256, 256)

In [3]:
for i, row in enumerate(im):
    for j, pixel in enumerate(row):
        if pixel < 10:
            im[i][j] = 1000
cv2.imwrite('out2.jpg', im)

True

In [48]:
im_splits = ['dataset_black_bg', 'Apple___Apple_scab', '0a5e9323-dbad-432d-ac58-d291718345d9___FREC_Scab 3417.JPG']
im_splits

['dataset_black_bg',
 'Apple___Apple_scab',
 '0a5e9323-dbad-432d-ac58-d291718345d9___FREC_Scab 3417.JPG']

In [53]:
im_splits[2][:-4] + '_final_masked.jpg'

'0a5e9323-dbad-432d-ac58-d291718345d9___FREC_Scab 3417_final_masked_final_masked.jpg'

In [54]:
base + im_splits[1] + '/' + im_splits[2][:-4] + '_final_masked.jpg'

'dataset_black_bg/Apple___Apple_scab/0a5e9323-dbad-432d-ac58-d291718345d9___FREC_Scab 3417_final_masked_final_masked.jpg'

In [56]:
base = 'dataset_black_bg/'
im = cv2.imread(base + im_splits[1] + '/' + im_splits[2][:-4] + '_final_masked.jpg', cv2.IMREAD_GRAYSCALE)
print(im.shape)
toimage(im)

AttributeError: 'NoneType' object has no attribute 'shape'

In [57]:
cam = cv2.imread('/home/lux/dev/Bachelor-2017/keras/maps_test_tf/Corn_(maize)___Common_rust_/RS_Rust 2307.JPG/0.tiff', cv2.IMREAD_UNCHANGED)

In [59]:
cam

array([[ 4.9395647 ,  4.92488098,  4.91050339, ...,  9.66814041,
         9.71024227,  9.73681736],
       [ 4.4623065 ,  4.45103979,  4.439991  , ...,  9.15616798,
         9.1983881 ,  9.22504044],
       [ 3.92839313,  3.92069268,  3.91308141, ...,  8.61110973,
         8.65342712,  8.68013954],
       ..., 
       [-7.90457726, -7.67491913, -7.43872929, ..., -2.94662166,
        -2.89542675, -2.86311245],
       [-7.91056824, -7.68066072, -7.44422388, ..., -2.95086169,
        -2.89956093, -2.86718464],
       [-7.91435337, -7.68428755, -7.44769382, ..., -2.95353746,
        -2.90217352, -2.86974978]], dtype=float32)

In [60]:
cam.shape

(256, 256)

In [61]:
cam.mean()

2.8018188

In [65]:
files_path = glob('maps_test_tf' + "/*/*/*.tiff")
list_of_cams = []
for f_path in files_path:
    list_of_cams.append(cv2.imread(f_path, cv2.IMREAD_UNCHANGED).flatten())    

In [ ]:
n, bins, patches = plt.hist(list_of_cams, 1, normed=1, facecolor='green', alpha=0.75)
plt.show()

In [8]:
a = np.asarray([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
a += 1
a

array([2, 3, 4, 5])

In [10]:
a += a.min()
a

array([4, 5, 6, 7])